---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/cbrgm/authproxy

steps:
  - name: build
    pull: always
    image: golang:1.11-alpine
    environment:
      GO111MODULE: on
    commands:
      - apk add -U git make
      - make lint
      - make test
      - make build
    when:
      event:
        - push
        - tag
        - pull_request