// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TokenReviewSpec TokenReviewSpec contains the token being reviewed
// swagger:model TokenReviewSpec
type TokenReviewSpec struct {

	// token
	Token string `json:"token,omitempty"`
}

// Validate validates this token review spec
func (m *TokenReviewSpec) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TokenReviewSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TokenReviewSpec) UnmarshalBinary(b []byte) error {
	var res TokenReviewSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
