// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// UserInfo UserInfo contains information about the user
// swagger:model UserInfo
type UserInfo struct {

	// Any additional information provided by the authenticator
	Extra interface{} `json:"Extra,omitempty"`

	// The names of groups this user is a part of
	Groups []string `json:"Groups"`

	// A unique value that identifies this user across time. If this user is deleted and another user by the same name is added, they will have different UIDs
	UID string `json:"UID,omitempty"`

	// The name that uniquely identifies this user among all active users
	Username string `json:"Username,omitempty"`
}

// Validate validates this user info
func (m *UserInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserInfo) UnmarshalBinary(b []byte) error {
	var res UserInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
