// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AuthenticateHandlerFunc turns a function with the right signature into a authenticate handler
type AuthenticateHandlerFunc func(AuthenticateParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AuthenticateHandlerFunc) Handle(params AuthenticateParams) middleware.Responder {
	return fn(params)
}

// AuthenticateHandler interface for that can handle valid authenticate params
type AuthenticateHandler interface {
	Handle(AuthenticateParams) middleware.Responder
}

// NewAuthenticate creates a new http.Handler for the authenticate operation
func NewAuthenticate(ctx *middleware.Context, handler AuthenticateHandler) *Authenticate {
	return &Authenticate{Context: ctx, Handler: handler}
}

/*Authenticate swagger:route POST /authenticate auth authenticate

verifies user credentials

authenticates users

*/
type Authenticate struct {
	Context *middleware.Context
	Handler AuthenticateHandler
}

func (o *Authenticate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAuthenticateParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
