// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi authproxy OpenAPI
This is the api documentation for https://github.com/cbrgm/authproxy

Terms Of Service:

http://github.com/cbrgm/authproxy


    Schemes:
      https
    Host: cbrgm.net
    BasePath: /v1
    Version: 1.0
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
    Contact: <chris@cbrgm.net>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
