/*
 * authproxy OpenAPI
 *
 * This is the api documentation for https://github.com/cbrgm/authproxy
 *
 * API version: 1.0
 * Contact: chris@cbrgm.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// UserInfo contains information about the user
type UserInfo struct {
	// The name that uniquely identifies this user among all active users
	Username string `json:"Username,omitempty"`
	// A unique value that identifies this user across time. If this user is deleted and another user by the same name is added, they will have different UIDs
	UID string `json:"UID,omitempty"`
	// The names of groups this user is a part of
	Groups []string `json:"Groups,omitempty"`
	// Any additional information provided by the authenticator
	Extra *interface{} `json:"Extra,omitempty"`
}
