/*
 * authproxy OpenAPI
 *
 * This is the api documentation for https://github.com/cbrgm/authproxy
 *
 * API version: 1.0
 * Contact: chris@cbrgm.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Principal contains information about the user
type Principal struct {
	// The name that uniquely identifies this user among all active users
	Username string `json:"Username,omitempty"`
	// The pasword of the user
	Password string `json:"Password,omitempty"`
}
