/*
 * authproxy OpenAPI
 *
 * This is the api documentation for https://github.com/cbrgm/authproxy
 *
 * API version: 1.0
 * Contact: chris@cbrgm.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// TokenReviewRequest is issued by K8s to this service
type TokenReviewRequest struct {
	Kind string `json:"kind,omitempty"`
	APIVersion string `json:"APIVersion,omitempty"`
	Spec *TokenReviewSpec `json:"Spec,omitempty"`
	Status *TokenReviewStatus `json:"Status,omitempty"`
}
