/*
 * authproxy OpenAPI
 *
 * This is the api documentation for https://github.com/cbrgm/authproxy
 *
 * API version: 1.0
 * Contact: chris@cbrgm.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// TokenReviewStatus is the result of the token authentication request
type TokenReviewStatus struct {
	// Authenticated is true if the token is valid
	Authenticated bool `json:"Authenticated,omitempty"`
	User *UserInfo `json:"User,omitempty"`
}
