/*
 * authproxy OpenAPI
 *
 * This is the api documentation for https://github.com/cbrgm/authproxy
 *
 * API version: 1.0
 * Contact: chris@cbrgm.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// TokenReviewSpec contains the token being reviewed
type TokenReviewSpec struct {
	Token string `json:"Token,omitempty"`
}
